// Prebuild: inline KaTeX fonts (woff2 only) as base64, pre-render Markdown content with KaTeX,
// and write build info (date + git commit).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import katex from 'katex';
import { marked } from 'marked';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const gen = join(root, 'src', 'generated');
mkdirSync(gen, { recursive: true });

// ---------- KaTeX CSS with embedded woff2 fonts ----------
const kdir = join(root, 'node_modules', 'katex', 'dist');
let css = readFileSync(join(kdir, 'katex.min.css'), 'utf8');
css = css.replace(/src:url\(fonts\/([^)]+?)\.woff2\) format\("woff2"\)(,url\([^)]+\) format\("[^"]+"\))*/g, (_, name) => {
  const b64 = readFileSync(join(kdir, 'fonts', name + '.woff2')).toString('base64');
  return `src:url(data:font/woff2;base64,${b64}) format("woff2")`;
});
if (/url\(fonts\//.test(css)) throw new Error('KaTeX CSS still references external font files');
writeFileSync(join(gen, 'katex.css'), css);

// ---------- Markdown + KaTeX ----------
const slug = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/<[^>]+>/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
let texErrors = 0;
function mathSpan(tex, display) {
  // Validate at build time; render at runtime with the bundled KaTeX (keeps the single file small).
  try {
    katex.renderToString(tex, { displayMode: display, throwOnError: true, strict: 'ignore' });
  } catch (e) {
    texErrors++;
    console.warn('KaTeX error:', e.message.slice(0, 120));
  }
  return `<span class="mtex${display ? ' d' : ''}">${esc(tex)}</span>`;
}
function renderMd(md) {
  const math = [];
  // display math first, then inline math. Avoid matching escaped \$.
  md = md.replace(/\$\$([\s\S]+?)\$\$/g, (_, tex) => {
    math.push(mathSpan(tex.trim(), true));
    return `@@MATH${math.length - 1}@@`;
  });
  md = md.replace(/(^|[^\\$])\$([^$\n]+?)\$/g, (_, pre, tex) => {
    math.push(mathSpan(tex.trim(), false));
    return `${pre}@@MATH${math.length - 1}@@`;
  });
  const toc = [];
  const used = new Set();
  const renderer = new marked.Renderer();
  renderer.heading = function ({ tokens, depth }) {
    const text = this.parser.parseInline(tokens);
    let id = slug(text.replace(/@@MATH\d+@@/g, '')) || 'sectie';
    while (used.has(id)) id += '-x';
    used.add(id);
    if (depth <= 3) toc.push({ depth, id, text: text.replace(/<[^>]+>/g, '').replace(/@@MATH\d+@@/g, '') });
    return `<h${depth} id="${id}">${text}</h${depth}>\n`;
  };
  let html = marked.parse(md, { renderer, gfm: true });
  html = html.replace(/<!--\s*tool:\s*([a-z]+)\s*-->/g, (_, id) => `<a class="open-tool" href="#/${id}">Open in tool &rarr;</a>`);
  html = html.replace(/@@MATH(\d+)@@/g, (_, i) => math[+i]);
  html = html.replace(/<table>/g, '<div class="tablewrap"><table>').replace(/<\/table>/g, '</table></div>');
  // Restore TOC text math tokens (plain)
  return { html, toc };
}

function load(p, fallback) {
  const f = join(root, p);
  return existsSync(f) ? readFileSync(f, 'utf8') : fallback;
}
const formularium = renderMd(load('content/formularium.md', '# Formularium\n\nNog niet beschikbaar.'));
const spiek = renderMd(load('content/spiekbrief.md', '# Spiekbrief\n\nNog niet beschikbaar.'));
const examMd = load('content/voorbeeldexamen_oplossingen.md', '');
const examQ = load('reference/voorbeeldexamen.md', '');
function splitQuestions(md) {
  const parts = {};
  const re = /^##\s+Vraag\s+(\d+)[^\n]*\n([\s\S]*?)(?=^##\s+Vraag\s+\d+|(?![\s\S]))/gm;
  let m;
  while ((m = re.exec(md))) parts[m[1]] = renderMd(m[2]).html;
  return parts;
}
const exam = { questions: splitQuestions(examQ), solutions: splitQuestions(examMd) };

writeFileSync(
  join(gen, 'content.ts'),
  `// Generated by scripts/prebuild.mjs - do not edit\nexport const formularium = ${JSON.stringify(formularium)};\nexport const spiekbrief = ${JSON.stringify(spiek)};\nexport const exam: { questions: Record<string, string>; solutions: Record<string, string> } = ${JSON.stringify(exam)};\n`,
);

// ---------- Build info ----------
let commit = 'geen-git';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  const dirty = execSync('git status --porcelain', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  if (dirty) commit += '+wijzigingen';
} catch {}
const date = new Date().toISOString().slice(0, 16).replace('T', ' ');
writeFileSync(join(gen, 'buildinfo.ts'), `export const BUILD = ${JSON.stringify({ date, commit })};\n`);
if (texErrors) console.warn(`${texErrors} KaTeX error(s)`);
console.log('prebuild ok:', { texErrors, formulariumToc: formularium.toc.length, examQ: Object.keys(exam.questions).length, examSol: Object.keys(exam.solutions).length, commit });
